In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/customer.csv')

In [ ]:
df.sample(5)

    age  gender   review education purchased
24   16  Female  Average        PG       Yes
2    70  Female     Good        PG        No
35   74    Male     Poor    School       Yes
39   76    Male     Poor        PG        No
22   18  Female     Poor        PG       Yes

In [ ]:
df=df.iloc[:,2:]

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop('purchased',axis=1),df['purchased'],
                                               test_size=0.3,
                                               random_state=0
                                               )

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
X_train

     review education
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG
15     Poor        UG
30  Average        UG
32  Average        UG
16     Poor        UG
42     Good        PG
20  Average    School
43     Poor        PG
8   Average        UG
13  Average    School
25     Good    School
5   Average    School
17     Poor        UG
40     Good    School
49     Good        UG
1      Poor        UG
12     Poor    School
37  Average        PG
24  Average        PG
6      Good    School
23     Good    School
36     Good        UG
21  Average        PG
19     Poor        PG
9      Good        UG
39     Poor        PG
46     Poor        PG
3      Good        PG
0   Average    School
47     Good        PG
44  Average        UG

In [ ]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
X_train

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [ ]:
y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])